version: 2

jobs:
  lint:
    working_directory: ~/project
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Lint
          command: npm ci && npm run lint
  test:
    working_directory: ~/project
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Run
          command: npm ci && npm run test
  deploy:
    working_directory: ~/project
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Run
          command: echo "Deploy Complete"
workflows:
  version: 2
  lint-test:
    jobs:
      - lint
      - test
  lint-test-deploy:
    jobs:
      - lint
      - test:
          requires:
            - lint
      - approve:
          type: approval
          requires:
            - lint
            - test
      - deploy:
          requires:
            - approve
